apiVersion: v1
kind: Service
metadata:
  name: alerta-cego
  namespace: observability-lab
spec:
  selector:
    app: alerta-cego
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
