name: Deploy to local Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t alerta-cego .

    - name: Create Kubernetes Secret and ConfigMap
      run: |
        kubectl create secret generic alerta-cego-secret \
          --from-literal=NEW_RELIC_LICENSE_KEY=${{ secrets.NEW_RELIC_LICENSE_KEY }} \
          --dry-run=client -o yaml | kubectl apply -f -

        kubectl create configmap alerta-cego-config \
          --from-literal=NEW_RELIC_APP_NAME=alerta-cego \
          --from-literal=NEW_RELIC_LOG_LEVEL=info \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Wait for rollout
      run: |
        kubectl rollout status deployment/alerta-cego

    - name: Done
      run: |
        echo "Deploy finalizado no cluster local (Docker Desktop)"
        echo "Acesse via NodePort ou use port-forward para testar."
        echo "Para anotar o deploy no New Relic, rode: ./scripts/annotate-deploy.sh"
